apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-orchestrator-service App
name: civil-orchestrator-service
home: https://github.com/hmcts/civil-orchestrator-service
version: 0.0.14
maintainers:
  - name: HMCTS civil team
dependencies:
  - name: java
    version: 4.1.4
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: civil-service
    version: 0.0.48
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: civil-service.enabled
  - name: ccd
    version: 8.0.29
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.enabled
  - name: xui-webapp
    version: ~1.0.8
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
  - name: camunda-bpm
    version: 0.0.39
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: camunda-bpm.enabled
