ccd:
  enabled: false

postgresql:
  enabled: false

idam-pr:
  enabled: false

xui-webapp:
  enabled: false

camunda-bpm:
  enabled: false

civil-service:
  enabled: false

java:
  applicationPort: 9090
  image: 'hmctspublic.azurecr.io/civil/orchestrator-service:latest'
  ingressHost: civil-orchestrator-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
#  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    civil:
      secrets:
        - name: microservicekey-civil-service
            alias: idam.s2s-auth.totp_secret
        - name: civil-idam-client-secret
            alias: idam.client.secret
        - name: system-update-user-username
            alias: CIVIL_SYSTEM_UPDATE_USERNAME
        - name: system-update-user-password
            alias: CIVIL_SYSTEM_UPDATE_PASSWORD
  environment:
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
    IDAM_CLIENT_ID: civil-service
    IDAM_CLIENT_REDIRECT_URI: https://civil-orchestrator-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_SECURITY_ENABLED: true
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
    CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_SECURED: true
    FEIGN_CLIENT_CONFIG_REMOTERUNTIMESERVICE_URL: http://${SERVICE_NAME}-camunda/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEEXTERNALTASKSERVICE_URL: http://${SERVICE_NAME}-camunda/engine-rest/
    FEIGN_CLIENT_CONFIG_REMOTEREPOSITORYSERVICE_URL: http://${SERVICE_NAME}-camunda/engine-rest/
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    SPRING_CLOUD_BOOTSTRAP_ENABLED: true
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
